spring:
  datasource:
    url: jdbc:mysql://localhost/codedb
    username: root
    password: thecure7
    driverClassName: com.mysql.jdbc.Driver
    continueOnError: true
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 25200000 #7*60*60*1000
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update

